name: CheckLabels
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, reopened, synchronize]

jobs:
  check_labels_job:
    runs-on: ubuntu-latest
    name: Fail Check If Labels Present
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Check Labels
        uses: ./.github/actions/checkLabels
